name:
  "Iterdir timing test"


on:
  workflow_dispatch:
  push:
    branches: ["main"]
    
jobs:
  compare_times:
    name: "Compare os.listdir v os.scandir implementations of Path.iterdir"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13.0-alpha.4' 
    - run: python Path_iterdir_scandir_test.py